version: "3.8"

services:
  frontend:
    image: claytonkpr/front-lista-tarefas:latest
    container_name: frontend
    restart: always
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - lista-tarefas

  backend:
    image: claytonkpr/back-lista-tarefas:latest
    container_name: backend
    restart: always
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://database:5432/lista-tarefas
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
    ports:
      - "8085:8085"
    depends_on:
      - database
    networks:
      - lista-tarefas

  database:
    image: postgres:latest
    container_name: database
    restart: always
    environment:
      POSTGRES_DB: lista-tarefas
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - volume-lista-tarefas:/var/lib/postgresql/data
    networks:
      - lista-tarefas

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "15432:80"
    depends_on:
      - database
    networks:
      - lista-tarefas

networks:
  lista-tarefas:
    driver: bridge

volumes:
  volume-lista-tarefas:
